### ISSUE TITLE
Utah not working for lookup

### ISSUE THREAD

**Issue by coreyb42** [unitedstates/python-us#13]
Basically here's the deal (looking up "Utah" or "utah" returns None, but looking up with "UT" or "uta" returns the proper state object):

    >>> us.states.lookup(u'UT')
    <State:Utah>
    >>> us.states.lookup(u'uta')
    <State:Utah>
    >>> us.states.lookup(u'Utah')
    >>> us.states.lookup(u'utah')
    >>> us.states.lookup(u'New Mexico')
    <State:New Mexico>

This is with 0.9.1.

**Comment by savraj** [comment]
Yes, I have the same issue, just hit it. Funny, I also searched for New Mexico to make sure other states worked...

REPRO STEPS:
>>>us.states.lookup(u"Utah")

EXPECTED RESULT: <State:Utah>
ACTUAL RESULT: None

**Comment by savraj** [comment]
Here's a hacky workaround, when you are looking for Utah, pass the field for an exact match:
`us.states.lookup(u"Utah",field='name')`-- case sensitive but returns correct result

**Comment by jcarbaugh** [comment]
@coreyb42 @savraj: could you tell me what platform you are running this on and what version of jellyfish you have installed? Also, are you using PyPy or CPython? I just pushed some additional tests and noticed that lookup is returning None on PyPy.

If the issue is a problem between PyPy and the jellyfish dependency then I'd be inclined to drop support for PyPy.

**Comment by savraj** [comment]
It works fine when __init__.py in jellyfish imports .cjellyfish (returns 'UT') and it doesn't work when jellyfish can't find .cjellyfish and instead imports ._jellyfish (returns 'UTH').  As my code runs on Google App Engine, .cjellyfish isn't permitted, from what I understand.

Here's my environment:
Python 2.7.10 (default, Oct 23 2015, 18:05:06) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin

**Comment by jcarbaugh** [comment]
@savraj a yeah, you are right. It's a bug in the Python implementation of metaphone, but the C implementation is correct. When installed on CPython it will use the C code, but PyPy uses the Python version. I guess App Engine also doesn't work with arbitrarily built C extensions, so it uses the buggy implementation as well. I'll look into submitting a patch to jellyfish.

**Comment by savraj** [comment]
Cool, glad we got to the bottom of this so fast. ;)
