### ISSUE TITLE
Some extra states

### ISSUE THREAD

**Issue by KiUserExceptionDispatcher** [unitedstates/python-us#25]
Based on: https://simple.wikipedia.org/wiki/U.S._postal_abbreviations
```

EXTRA_STATES = {
	'Armed Forces Americas': 'AA',
	'Armed Forces Europe': 'AE',
	'Armed Forces Canada': 'AE',
	'Armed Forces Middle East': 'AE',
	'Armed Forces Africa': 'AE',
	'Armed Forces Pacific': 'AP',
	'Federated States Of Micronesia': 'FM',
	'Marshall Islands': 'MH',
	'Palau': 'PW',
}
```

**Comment by jcarbaugh** [comment]
@KiUserExceptionDispatcher thanks for the suggestion! Federated States Of Micronesia, Marshall Islands, and Palau are independent countries, so I don't think they meet the threshold for inclusion in us. I'm open to considering the Armed Forces ones, but am not sure if they have most of the attributes that this package was meant to provide. I'm closing for now, but if you have a specific use case for them, I'm happy to consider again!
