### ISSUE TITLE
OBSOLETE included in STATES_AND_TERRITORIES

### ISSUE THREAD

**Issue by mayoroftuesday** [unitedstates/python-us#26]
Not sure if this is intentional, but it is odd behavior.

`set(us.states.STATES_AND_TERRITORIES) == set(us.states.STATES + us.states.TERRITORIES + us.states.OBSOLETE)`

I would expect STATES_AND_TERRITORIES to be just STATES + TERRITORIES

**Comment by jcarbaugh** [comment]
@mayoroftuesday completely agree! I'm working on a new version of us and will make this change there. Thanks!
