### ISSUE TITLE
sqlite to code

### ISSUE THREAD

**Issue by jcarbaugh** [unitedstates/python-us#37]
Due to ease of merging and other issues, I'm thinking the sqlite + pkl file no longer makes sense. The original intention was to have easier modification of data, but merging multiple changes to the database is pretty much impossible without manual intervention.

I'm thinking it's time to just convert it all to Python with a class for each state. Any thoughts @mileswwatkins?

**Comment by mileswwatkins** [comment]
That feels more readable to me, and easier to review changes (thinking similar to reviewing modifications to the OCD Division ID set; that'd be hard if PRs weren't in plaintext).

**Comment by mileswwatkins** [comment]
To clarify, this refactor would be towards a single Python file with a class instance for each US state/territory, looking something like:

```python
USEntity(
    name='Montana',
    fips='30',
    is_territory=False,
    time_zones=[
        'America/Denver'
    ],
    ...
)
```

with a handful of properties calculated automatically within the class, such as the metaphone and TIGER/Line shapefile URIs?
