### ISSUE TITLE
Timezone Inconsistencies

### ISSUE THREAD

**Issue by iPatso** [unitedstates/python-us#48]
Using this package for just the state to timezone(s) info, it seems there are missing and incorrect timezones.

Some that I have found:
- IN: Missing `America/Chicago` and `America/New_York`. Just outdated overall.
- KY: Missing `America/Chicago`. Unnecessary `America/Louisville` (has `America/Kentucky/Louisville`)
- NM: Should be `America/Denver`, not `America/Chicago`.

These are only a few, so there must be more inconsistencies around with other state timezone(s).

**Comment by jcarbaugh** [comment]
@iPatso I'll make these changes in the branch I'm working on for a 2.0 release. Thanks!
