### ISSUE TITLE
Installation Fails with Python 2.7

### ISSUE THREAD

**Issue by dylanmann** [unitedstates/python-us#49]
I don't find any mention of dropping python 2 support in the changelog for 2.0.0, but installing with pip fails due to the `jellyfish==0.7.2` requirement.

Could you either document that you're dropping support or fix this dependency issue?

```
> pip install us==2.0.0
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting us==2.0.0
  Downloading us-2.0.0.tar.gz (13 kB)
ERROR: Could not find a version that satisfies the requirement jellyfish==0.7.2 (from us==2.0.0) (from versions: 0.1, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.6.0, 0.6.1)
ERROR: No matching distribution found for jellyfish==0.7.2 (from us==2.0.0)
```

**Comment by jcarbaugh** [comment]
Ah, sorry! Looks like I was accidentally running Python 2.7 tests with Python 3 and they were falsely passing. Updating now to revert to jellyfish 0.6.1 and will get a new release out.

Version 3.0 of this package will likely drop Python 2 support, so please pin your version <3.0. Thanks!

**Comment by jcarbaugh** [comment]
@dylanmann just pushed v2.0.1 to PyPI which should support Python 2.7. Please let me know if that works for you now.

**Comment by dylanmann** [comment]
Looks like that worked for us, thanks for the quick fix!
