### ISSUE TITLE
Push to pypi?

### ISSUE THREAD

**Issue by adamkgoldfarb** [unitedstates/python-us#55]
Hello! I love, and indeed have always loved, this package.

2.0.2 has an old jellyfish dependency, however, and I see that 3 has been pushed with a jellyfish upgrade.

I could install from github but was wondering if you intend to push to pypi soon-- if so, I can hold on.

Thanks!

**Comment by ablacklama** [comment]
same here. I'm looking at those typed State attributes with longing 😄

**Comment by AdeelK93** [comment]
+1!

**Comment by rposborne** [comment]
@adamkgoldfarb 3.0.1 Has been pushed to pypi. This can be closed! 🎆

**Comment by adamkgoldfarb** [comment]
> @adamkgoldfarb 3.1.1 Has been pushed to pypi. This can be closed! 🎆 

Hurrah! Thanks so much!
