### ISSUE TITLE
Cut the 3.0 release

### ISSUE THREAD

**Issue by rposborne** [unitedstates/python-us#63]
How can we help cut the 3.0 release so we can push for 3.9 and 3.10 support?

**Comment by Zaba107** [comment]
Interested in the same. Looking for 3.10 support.

**Comment by voxvici** [comment]
Same

**Comment by pauldhawk** [comment]
same

**Comment by jcarbaugh** [comment]
Hi all, thanks to nudging by @pauldhawk a 3.1.1 release has been uploaded to PyPI.
