### ISSUE TITLE
Incompatible with Python 3.12 because of jellyfish 0.11.2 dependency

### ISSUE THREAD

**Issue by tomoforest** [unitedstates/python-us#75]
Hello, I attempted to install the us package in my Python 3.12.1 environment using Poetry 1.7.0 and the install failed to build the jellyfish 0.11.2 package. This is a known issue in jellyfish that was resolved as of 1.0.3, can we get a new build of us with the updated dependency?

https://github.com/jamesturk/jellyfish/issues/199#issuecomment-1817088895

Also I see that someone has created a PR to do this very thing https://github.com/unitedstates/python-us/pull/74

**Comment by OttoAndrey** [comment]
If you got same error as I did 
<img width="698" alt="image" src="https://github.com/unitedstates/python-us/assets/30920379/665845bb-2992-4a3f-b5a2-40c56a395367">

You can try install [Cargo](https://doc.rust-lang.org/cargo/getting-started/installation.html). For me it helped

**Comment by pedrocamargo** [comment]
This is indeed becoming an issue, as Python 3.12 is the default Python version on Ubuntu 24.04, and QGIS has also moved to Python 3.12

I have fixed the issue and added some needed software engineering to fix this all.  
https://github.com/unitedstates/python-us/pull/78

**Comment by pedrocamargo** [comment]
@tomoforest and @OttoAndrey , I am thinking of forking the project and releasing it under a different name on PyPI. Do you see another alternative?

**Comment by jcarbaugh** [comment]
us 3.2.0 with support for Python 3.12 has just been published to PyPI https://pypi.org/project/us/

Please let me know if there are any lingering issues!
